# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-14 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('smallImg', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('sales', models.CharField(max_length=100)),
                ('oldprice', models.FloatField()),
                ('store', models.IntegerField()),
                ('background', models.CharField(max_length=100)),
            ],
        ),
    ]
