# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-14 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgj', '0002_productdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
