# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-15 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgj', '0005_auto_20190315_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productnumber', models.IntegerField()),
                ('isselect', models.BooleanField(default=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('productdetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mgj.Productdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mgj.User')),
            ],
        ),
    ]
