# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-15 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgj', '0006_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
