# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-16 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgj', '0007_productdetail_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
                ('orderid', models.CharField(max_length=256)),
                ('uesr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mgj.User')),
            ],
        ),
        migrations.CreateModel(
            name='Orderproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mgj.Order')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mgj.Productdetail')),
            ],
        ),
    ]
