# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-16 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgj', '0008_order_orderproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='uesr',
            new_name='user',
        ),
    ]
