# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-16 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgj', '0009_auto_20190316_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordermoney',
            field=models.FloatField(default=0),
        ),
    ]
