# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-18 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgj', '0013_auto_20190318_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cartmoney',
            field=models.FloatField(default=0),
        ),
    ]
