# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-18 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgj', '0014_auto_20190318_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordermoney',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='oldprice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='price',
            field=models.FloatField(),
        ),
    ]
