# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-19 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgj', '0016_auto_20190318_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordermoney',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
